"""catalog drafts and product requests

Revision ID: 542d49075396
Revises: 7c9e47b16090
Create Date: 2026-09-19 21:17:48.212011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '542d49075396'
down_revision: Union[str, None] = '7c9e47b16090'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_drafts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('items', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'applied', 'discarded', name='catalog_draft_status'), nullable=False),
    sa.Column('inserted', sa.Integer(), nullable=False),
    sa.Column('updated', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_catalog_drafts_business_id_businesses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_catalog_drafts'))
    )
    op.create_index(op.f('ix_catalog_drafts_business_id'), 'catalog_drafts', ['business_id'], unique=False)
    op.create_table('product_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('query', sa.String(length=160), nullable=False),
    sa.Column('query_key', sa.String(length=160), nullable=False),
    sa.Column('times_asked', sa.Integer(), nullable=False),
    sa.Column('last_retailer_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('open', 'added', 'dismissed', name='product_request_status'), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=True),
    sa.Column('first_asked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_asked_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_product_requests_business_id_businesses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['last_retailer_id'], ['retailers.id'], name=op.f('fk_product_requests_last_retailer_id_retailers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_requests_product_id_products'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_requests')),
    sa.UniqueConstraint('business_id', 'query_key', name=op.f('uq_product_requests_business_id_query_key'))
    )
    op.create_index(op.f('ix_product_requests_business_id'), 'product_requests', ['business_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_requests_business_id'), table_name='product_requests')
    op.drop_table('product_requests')
    op.drop_index(op.f('ix_catalog_drafts_business_id'), table_name='catalog_drafts')
    op.drop_table('catalog_drafts')
    # ### end Alembic commands ###
