"""auto reply and reply text

Revision ID: 7c9e47b16090
Revises: 8c291a4e5b20
Create Date: 2026-09-19 20:59:46.982475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7c9e47b16090'
down_revision: Union[str, None] = '8c291a4e5b20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('auto_reply', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('orders', sa.Column('reply_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'reply_text')
    op.drop_column('businesses', 'auto_reply')
    # ### end Alembic commands ###
